# -*- coding: utf-8 -*-
"""Personal Portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9eovsodOzO9pmx0J5-yXVnAK9j3IC1S
"""

from IPython.display import HTML

HTML("""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Personal Portfolio</title>

<style>
*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family:Arial, sans-serif;
}

body{
    background:#f4f4f4;
}

header{
    background:linear-gradient(135deg,#6a11cb,#2575fc);
    color:white;
    text-align:center;
    padding:40px;
}

nav{
    background:#333;
    padding:15px;
    text-align:center;
}

nav a{
    color:white;
    text-decoration:none;
    margin:15px;
    font-weight:bold;
}

.container{
    display:flex;
    flex-wrap:wrap;
    justify-content:center;
    gap:20px;
    padding:30px;
}

.card{
    background:white;
    width:300px;
    padding:20px;
    border-radius:10px;
    box-shadow:0 4px 8px rgba(0,0,0,0.2);
    transition:0.3s;
}

.card:hover{
    transform:translateY(-8px);
}

h2{
    color:#2575fc;
    margin-bottom:10px;
}

.btn{
    display:inline-block;
    background:#2575fc;
    color:white;
    padding:10px 20px;
    text-decoration:none;
    border-radius:5px;
    margin-top:10px;
    transition:0.3s;
}

.btn:hover{
    background:#6a11cb;
}

footer{
    background:#333;
    color:white;
    text-align:center;
    padding:15px;
    margin-top:20px;
}

@media(max-width:768px){
    .container{
        flex-direction:column;
        align-items:center;
    }

    .card{
        width:90%;
    }
}
</style>
</head>

<body>

<header>
    <h1>Kiruthika Shree</h1>
    <p>Computer Science Engineering Student</p>
</header>

<nav>
    <a href="#about">About</a>
    <a href="#skills">Skills</a>
    <a href="#projects">Projects</a>
    <a href="#contact">Contact</a>
</nav>

<div class="container">

<div class="card" id="about">
    <h2>About Me</h2>
    <p>
    Hello! I am Kiruthika Shree, a first-year CSE student.
    I am passionate about web development and learning new technologies.
    </p>
</div>

<div class="card" id="skills">
    <h2>Skills</h2>
    <ul>
        <li>HTML</li>
        <li>CSS</li>
        <li>JavaScript (Beginner)</li>
        <li>Bootstrap</li>
    </ul>
</div>

<div class="card" id="projects">
    <h2>Projects</h2>
    <p><b>Personal Portfolio Website</b></p>
    <p>A responsive portfolio website built using HTML and CSS.</p>
    <a href="#" class="btn">View Project</a>
</div>

<div class="card" id="contact">
    <h2>Contact</h2>
    <p>Email: yourmail@gmail.com</p>
    <p>LinkedIn: linkedin.com/in/yourprofile</p>
    <a href="#" class="btn">Connect</a>
</div>

</div>

<footer>
    <p>© 2026 Kiruthika Shree | Portfolio Website</p>
</footer>

</body>
</html>
""")